### ISSUE TITLE
toSparql skips part of algebra

### ISSUE THREAD

**Issue by qootec** [joachimvh/SPARQLAlgebra.js#116]
Doing some tests with translate followed by toSparql, I run into an issue where a part of the query disappears.
Am I overlooking something or is this an issue in the SPARQLAlgebra libray?
See attached reproduction (as txt instead of js since the latter is not supported as attachment).
[test_toSparql.txt](https://github.com/user-attachments/files/15841319/test_toSparql.txt)

**Comment by joachimvh** [comment]
This does indeed seem to be a bug with the library

**Comment by joachimvh** [comment]
This is fixed in v4.3.6. The problem should be gone when you reset your lock file.
