### ISSUE TITLE
Serialize output to SPARQL string

### ISSUE THREAD

**Issue by rubensworks** [joachimvh/SPARQLAlgebra.js#12]
How feasible would it be to support serializing a SPARQL algebra tree to a SPARQL string again?
(Not necessarily guaranteeing the same output as the original input)

**Comment by joachimvh** [comment]
Theoretically this should be possible I think. The actual string might be vastly different from the input string though. Not sure yet how much work this would be, would have to investigate.

**Comment by joachimvh** [comment]
This is solved in v0.7.0. There are a few specific cases that don't work, that depend on SPARQL.js updating, but these are edge cases anyway.
