### ISSUE TITLE
Support custom prefixes in translate

### ISSUE THREAD

**Issue by rubensworks** [joachimvh/SPARQLAlgebra.js#20]
SPARQL.js supports providing custom prefixes (and a baseIRI) in the [Parser constructor](https://github.com/RubenVerborgh/SPARQL.js/blob/master/sparql.js#L10). This option is however not exposed in the `translate` function of this library.

**Comment by joachimvh** [comment]
Huh, didn't even know you could do that. :D Will have to look into that.

**Comment by joachimvh** [comment]
Fixed in 9f4c2f8f24d189ad44060d88908d7a646fc6b840
