### ISSUE TITLE
DESCRIBE * does not return variables

### ISSUE THREAD

**Issue by rubensworks** [joachimvh/SPARQLAlgebra.js#23]
According to the [spec](https://www.w3.org/TR/rdf-sparql-query/#describe), a `DESCRIBE *` query should describe all variables in the `WHERE` clause. However, the `terms` always contains only a single element: `NamedNode { value: '*' }`.

**Comment by joachimvh** [comment]
Fixed in c1ad5edb3919a8c76412b13792ed737e8b6ae7c9 (v0.7.2).
