### ISSUE TITLE
Support SERVICE keyword

### ISSUE THREAD

**Issue by rubensworks** [joachimvh/SPARQLAlgebra.js#25]
Would it be possible to add support for adding support for the [SERVICE](https://www.w3.org/TR/sparql11-federated-query/) keyword? I need it for _things_...

**Comment by joachimvh** [comment]
Starting to wonder if I should maybe make different versions with all these non-algebra things that get added

**Comment by joachimvh** [comment]
Apparently there is an algebra spec for SERVICE!

Added in 4bad957c83d00a5db79c594cf9eec6f0421f2b52 (v0.7.4)
