### ISSUE TITLE
Support FROM and FROM NAMED

### ISSUE THREAD

**Issue by rubensworks** [joachimvh/SPARQLAlgebra.js#26]
It looks like the `FROM` and `FROM NAMED` keywords are ignored at the moment.

This causes queries such as `SELECT * FROM <http://ex> { ?s ?p ?o }` to be evaluated in the default graph, which is not very correct.

**Comment by joachimvh** [comment]
Another one of those keywords that's actually not covered by the algebra so it's totally cheating to add it. I'll see what the best way to add it is.

**Comment by joachimvh** [comment]
Added in v0.7.5
