### ISSUE TITLE
Require of translate does not work

### ISSUE THREAD

**Issue by rubensworks** [joachimvh/SPARQLAlgebra.js#6]
Something like this (in TS) gives an error that it can't find `translate`:
```
import {Pattern, translate} from "sparqlalgebrajs";
```

Possibly introduced in 9ce9d4560970ad4302a9bc5d2dff9411edc59c39.

It's going to be tricky to properly export the types *and* the translate function nicely.

**Comment by joachimvh** [comment]
bec63f7c updates the exports. The package only exports 2 objects now (which was the original intent actually): translate and Algebra with all typings being contained within the Algebra object. Also changed the imports in the test file to use the index file to make sure it works, but let me know if there is still a problem with this.

**Comment by rubensworks** [comment]
You should probably add an `index.js` file as well, otherwise only TS application will be able to work with it.

**Comment by joachimvh** [comment]
The javascript is present in the published package (isn't that how you're supposed to do it with typescript?)

**Comment by rubensworks** [comment]
Ah, yes indeed, the problem was that I imported this repo via GitHub, as I couldn't find it on npm.

**Comment by joachimvh** [comment]
Ah right, I'm publishing to Sinopia since I still have that set up as my registry, should probably change that :D

**Comment by joachimvh** [comment]
Also on npm now https://www.npmjs.com/package/sparqlalgebrajs
