### ISSUE TITLE
Error: Translate only works on complete query or update objects for empty updates

### ISSUE THREAD

**Issue by rubensworks** [joachimvh/SPARQLAlgebra.js#76]
The following queries are part of the SPARQL Update syntax tests:

```sparql
# Empty
```

```sparql
BASE <http://example/>
```

```sparql
PREFIX : <http://example/>
```

These are accepted by SPARQL.js, but throw an error with this lib:

> Error: Translate only works on complete query or update objects.

**Comment by joachimvh** [comment]
Not sure what best to return here since there isn't really an empty Algebra operation. Could just return an empty object of course, but this wouldn't be a valid algebra object since it has no type.

**Comment by rubensworks** [comment]
Would it make sense to introduce a no-op operator for this?
This would also require special handling in Comunica of course.

In any case, an error seems undesired, since the syntax is valid according to the spec tests.

**Comment by joachimvh** [comment]
I always try to avoid introducing new operations if possible, but I agree that would make sense.

I could also return a simple project + empty bgp (so the same result as `SELECT * WHERE {}`). A bit ugly since that's not really what happens but would require no changes in Comunica.

**Comment by rubensworks** [comment]
> I could also return a simple project + empty bgp

I would also be ok with that. For the end-user this would just producce an empty result, which should be fine.

Doesn't matter too much tbh, no one really expects a proper query result from an empty query anyways :-)

**Comment by joachimvh** [comment]
Fixed in 31ebc271233ad3fa9eda4f396c18cb052c9c3733
