### ISSUE TITLE
INSERT/DELETE USING semantics vs FROM semantics

### ISSUE THREAD

**Issue by rubensworks** [joachimvh/SPARQLAlgebra.js#77]
I just discovered in two SPARQL update tests that the current handling of the `USING` clause (and its rewriting to `FROM`) in this lib is incompatible with what the spec expects if the `GRAPH` clause is used.

[One example of a query](http://www.w3.org/2009/sparql/docs/tests/data-sparql11/delete/manifest#dawg-delete-using-06a) that proves this incompatibility is the following:
```sparql
PREFIX     : <http://example.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DELETE
{
  GRAPH <http://example.org/g2> { ?s ?p ?o }
}
USING <http://example.org/g3>
WHERE
{
  GRAPH <http://example.org/g2> { ?s foaf:name "Chris" .
                                  ?s ?p ?o }
}
```

The corresponding spec test description says:

> Test 2 for DELETE only modifying the desired graph making sure the GRAPH clause does not override the USING clause

However, this lib rewrites the `USING` clause by wrapping the BGP in a `FROM` clause. This works in the majority of cases, but not when a `GRAPH` clause is used.
This is because `GRAPH` _does_ override the `FROM` target, so it has a slightly different compared to `USING`.

One solution would be to strip away all the `GRAPH` clauses when `USING` is used. Another solution would be to just expose the `USING` clause at algebra-level, and let applications downstream handle it.
I would be fine with either option.

**Comment by joachimvh** [comment]
But doesn't the algebra let the downstream applications handle it by simply inserting the `from` operation? Unless you're saying `using` and `from` should be interpreted differently, but the reason it is done as it is now is because the spec says both should be identical:

> The USING and USING NAMED clauses affect the RDF Dataset used while evaluating the WHERE clause. This describes a dataset in the same way as FROM and FROM NAMED clauses describe RDF Datasets in the SPARQL 1.1 Query Language. The keyword USING instead of FROM in update requests is to avoid possible ambiguities which could arise from writing "DELETE FROM". That is, the GroupGraphPattern in the WHERE clause will be matched against the dataset described by explicit USING or USING NAMED clauses, if specified, and against the Graph Store otherwise.

**Comment by rubensworks** [comment]
> Unless you're saying using and from should be interpreted differently

That's indeed what I intended to say.

I also can't find any mention of this different interpretation in the spec though, so your quote of the spec may suggest a contradiction between the spec and the test suite. I'll open an issue at the test suite repo to ask for clarification.

**Comment by rubensworks** [comment]
So it looks like our (=my) interpretation of FROM/FROM NAMED was incorrect, so nothing needs to be changed here :-)
